### ISSUE TITLE
鉴黄可以直接使用官方的接口也是免费的

### ISSUE THREAD

**Issue by zhixinfang** [no1xuan/zjzNsfw#1]
鉴黄可以直接使用官方的接口也是免费的，填入APPID和秘钥就行

**Comment by no1xuan** [comment]
无需appid和密钥
阅读：https://github.com/no1xuan/HivisionIDPhotos-wechat-weapp

**Comment by no1xuan** [comment]
无需appid和密钥
阅读：https://github.com/no1xuan/HivisionIDPhotos-wechat-weapp
![微信截图_20241105172902](https://github.com/user-attachments/assets/3c7bb864-c30b-4b25-b4ee-e1df0c211b3d)

**Comment by zhixinfang** [comment]
我的意思是使用node搭建一个官方的接口，我现在用的就是
